In [1]:
#  import numpy as np

import numpy as np


Numpy Arrays

In [2]:
list1=[1,2,3,4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [3]:
#incase of numpy not seprated by comma
#nd=n-dimensional similar to matrix
np_array=np.array([1,2,3,4])
print(np_array)
print(type(np_array))

[1 2 3 4]
<class 'numpy.ndarray'>


creating 1d arrays

In [6]:
np_array=np.array([1,2,3,4])
print(np_array)
np_array.shape
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape
c=np.array([(1,2,3,4),(4,5,6,7)],dtype=float)
print(c)
#default datatype is int if u dont mention


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


initial placeholders

In [11]:
x=np.zeros((4,5))
print(x)
#create np values of 4 rows 5 colums with all zeros
# np array ones
y=np.ones((2,3))
print(y)
#array of a particular value
z=np.full((3,3),90)
print(z)
#create identity matrix
a=np.eye(4)# row=col for identity
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[90 90 90]
 [90 90 90]
 [90 90 90]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#numpy array with random values
b=np.random.random((3,4))
print(b)
#b/w 0 and 1

[[0.98131874 0.59418872 0.35733253 0.5837857 ]
 [0.55415565 0.04165373 0.43979489 0.90039457]
 [0.98430396 0.74508533 0.39979177 0.48454203]]


In [13]:
#random integers array
c=np.random.randint(10,50,(3,5))
print(c)


[[11 12 10 17 47]
 [11 47 36 27 27]
 [21 17 42 34 21]]


In [14]:
#array of evenly spaced values..also can specify no. of values required
d=np.linspace(10,50,5)
print(d)

[10. 20. 30. 40. 50.]


In [15]:
#specyfying step no.
e=np.arange(10,50,5)
#5= difference
print(e)

[10 15 20 25 30 35 40 45]


In [16]:
#covert list to numpy arraay
list2=[10,10,30,40,50]
np_Arr=np.asarray(list2)
print(np_Arr)
type(np_Arr)

[10 10 30 40 50]


numpy.ndarray

inspecting Numpy Arrays


In [19]:
arr1=np.random.randint(10,50,(4,4))
print(arr1)
print(arr1.shape)# return no. of rows and column
print(arr1.ndim)#return dimensions(2d array)
print(arr1.size)#no.of elements
print(arr1.dtype)#datatype-64 bit

[[24 27 40 40]
 [17 25 40 44]
 [32 34 45 13]
 [43 32 31 10]]
(4, 4)
2
16
int64


mathematical operations on NumpyArray

In [21]:
l=[1,2,3,4,5]
m=[6,7,8,9,10]
print(l+m)#concatenation not element wise adddition
p=np.random.randint(0,10,(3,3))
q=np.random.randint(10,20,(3,3))
print(p)
print(q)
print(p+q)#matrix addition
print(p*q) #matrix multiplication


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[1 0 6]
 [9 5 2]
 [3 5 0]]
[[15 16 17]
 [13 11 16]
 [19 13 14]]
[[16 16 23]
 [22 16 18]
 [22 18 14]]
[[ 15   0 102]
 [117  55  32]
 [ 57  65   0]]
